/**
 * Regenerates supabase/seed.sql from the bundled demo dataset in
 * src/lib/data/local. Run with `npm run db:seed:export` whenever the demo
 * dataset changes, so the SQL seed used by `supabase db reset` stays in
 * sync with what ships in the app by default.
 *
 * IDs are deterministic (uuid_generate_v5 over a stable "poliscope:<type>:<key>"
 * name) so foreign keys can be expressed inline without a lookup table.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { elections } from "../src/lib/data/local/elections";
import { parties } from "../src/lib/data/local/parties";
import { themes } from "../src/lib/data/local/themes";
import { candidates } from "../src/lib/data/local/candidates";
import { questions } from "../src/lib/data/local/questions";
import { candidatePositions } from "../src/lib/data/local/positions";
import { proposals } from "../src/lib/data/local/proposals";
import { polls, pollResults } from "../src/lib/data/local/polls";

function uuid(kind: string, key: string) {
  return `uuid_generate_v5(uuid_ns_url(), 'poliscope:${kind}:${key}')`;
}

function sqlString(value: string | null | undefined) {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNumber(value: number | null | undefined) {
  return value === null || value === undefined ? "null" : String(value);
}

function sqlBool(value: boolean) {
  return value ? "true" : "false";
}

const lines: string[] = [
  "-- Auto-generated by scripts/export-seed.ts — do not edit by hand.",
  "-- Regenerate with: npm run db:seed:export",
  "",
];

lines.push("-- elections");
for (const e of elections) {
  lines.push(
    `insert into elections (id, slug, name, kind, round_date, is_active) values (${uuid("election", e.slug)}, ${sqlString(e.slug)}, ${sqlString(e.name)}, ${sqlString(e.kind)}, ${sqlString(e.round_date)}, ${sqlBool(e.is_active)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- parties");
for (const p of parties) {
  const key = p.id.replace("party-", "");
  lines.push(
    `insert into parties (id, name, short_name, orientation, color) values (${uuid("party", key)}, ${sqlString(p.name)}, ${sqlString(p.short_name)}, ${sqlString(p.orientation)}, ${sqlString(p.color)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- themes");
for (const t of themes) {
  lines.push(
    `insert into themes (id, slug, name, description, icon, order_index) values (${uuid("theme", t.slug)}, ${sqlString(t.slug)}, ${sqlString(t.name)}, ${sqlString(t.description)}, ${sqlString(t.icon)}, ${t.order_index}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidates");
for (const c of candidates) {
  const partyKey = c.party_id?.replace("party-", "");
  const electionSlug = elections.find((e) => e.id === c.election_id)?.slug ?? elections[0].slug;
  lines.push(
    `insert into candidates (id, slug, name, photo_url, party_id, biography, official_website, election_id, is_demo, order_index) values (${uuid("candidate", c.slug)}, ${sqlString(c.slug)}, ${sqlString(c.name)}, ${sqlString(c.photo_url)}, ${partyKey ? uuid("party", partyKey) : "null"}, ${sqlString(c.biography)}, ${sqlString(c.official_website)}, ${uuid("election", electionSlug)}, ${sqlBool(c.is_demo)}, ${c.order_index}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- questions");
for (const q of questions) {
  const themeSlug = q.theme_id.replace("theme-", "");
  const choices = q.choices ? `'${JSON.stringify(q.choices).replace(/'/g, "''")}'::jsonb` : "null";
  lines.push(
    `insert into questions (id, theme_id, question, description, weight, answer_type, choices, order_index) values (${uuid("question", q.id)}, ${uuid("theme", themeSlug)}, ${sqlString(q.question)}, ${sqlString(q.description)}, ${q.weight}, ${sqlString(q.answer_type)}, ${choices}, ${q.order_index}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidate_positions");
for (const pos of candidatePositions) {
  const candidate = candidates.find((c) => c.id === pos.candidate_id)!;
  lines.push(
    `insert into candidate_positions (id, candidate_id, question_id, score, explanation, source_url) values (${uuid("position", pos.id)}, ${uuid("candidate", candidate.slug)}, ${uuid("question", pos.question_id)}, ${sqlNumber(pos.score)}, ${sqlString(pos.explanation)}, ${sqlString(pos.source_url)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- proposals");
for (const p of proposals) {
  const candidate = candidates.find((c) => c.id === p.candidate_id)!;
  const themeSlug = p.theme_id.replace("theme-", "");
  lines.push(
    `insert into proposals (id, candidate_id, theme_id, title, summary, description, source_name, source_url, published_at, verified_at, status) values (${uuid("proposal", p.id)}, ${uuid("candidate", candidate.slug)}, ${uuid("theme", themeSlug)}, ${sqlString(p.title)}, ${sqlString(p.summary)}, ${sqlString(p.description)}, ${sqlString(p.source_name)}, ${sqlString(p.source_url)}, ${sqlString(p.published_at)}, ${sqlString(p.verified_at)}, ${sqlString(p.status)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- polls");
for (const poll of polls) {
  const electionSlug = elections.find((e) => e.id === poll.election_id)?.slug ?? elections[0].slug;
  lines.push(
    `insert into polls (id, election_id, institute, sponsor, field_start, field_end, sample_size, method, round, published_at, is_demo) values (${uuid("poll", poll.id)}, ${uuid("election", electionSlug)}, ${sqlString(poll.institute)}, ${sqlString(poll.sponsor)}, ${sqlString(poll.field_start)}, ${sqlString(poll.field_end)}, ${poll.sample_size}, ${sqlString(poll.method)}, ${sqlString(poll.round)}, ${sqlString(poll.published_at)}, ${sqlBool(poll.is_demo)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- poll_results");
for (const r of pollResults) {
  const candidate = candidates.find((c) => c.id === r.candidate_id)!;
  lines.push(
    `insert into poll_results (id, poll_id, candidate_id, value, low, high) values (${uuid("poll_result", r.id)}, ${uuid("poll", r.poll_id)}, ${uuid("candidate", candidate.slug)}, ${r.value}, ${sqlNumber(r.low)}, ${sqlNumber(r.high)}) on conflict (id) do nothing;`
  );
}

const outPath = join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(outPath, lines.join("\n") + "\n", "utf-8");
console.log(`Wrote ${outPath}`);
