/**
 * Regenerates supabase/seed.sql from the bundled demo dataset in
 * src/lib/data/local. Run with `npm run db:seed:export` whenever the demo
 * dataset changes, so the SQL seed used by `supabase db reset` stays in
 * sync with what ships in the app by default.
 *
 * IDs are deterministic (uuid_generate_v5 over a stable "poliscope:<type>:<key>"
 * name) so foreign keys can be expressed inline without a lookup table.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { elections } from "../src/lib/data/local/elections";
import { parties } from "../src/lib/data/local/parties";
import { themes } from "../src/lib/data/local/themes";
import { candidates } from "../src/lib/data/local/candidates";
import { questions } from "../src/lib/data/local/questions";
import { candidatePositions } from "../src/lib/data/local/positions";
import { proposals } from "../src/lib/data/local/proposals";
import { polls, pollScenarios, pollResults } from "../src/lib/data/local/polls";
import {
  measureAnalyses,
  measureAssumptions,
  measureBudgetEstimates,
  measureImpacts,
} from "../src/lib/data/local/measure-analyses";
import {
  candidateCareers,
  candidateControversies,
  candidateLegalCases,
  candidateMandates,
  candidatePositionEvolutions,
  candidatePositionHistory,
  candidateTransparencyRecords,
  candidateVotes,
} from "../src/lib/data/local/candidate-records";

function uuid(kind: string, key: string) {
  return `uuid_generate_v5(uuid_ns_url(), 'poliscope:${kind}:${key}')`;
}

function sqlString(value: string | null | undefined) {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNumber(value: number | null | undefined) {
  return value === null || value === undefined ? "null" : String(value);
}

function sqlBool(value: boolean) {
  return value ? "true" : "false";
}

function sqlJson(value: unknown) {
  return value === null || value === undefined ? "null" : `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

const lines: string[] = [
  "-- Auto-generated by scripts/export-seed.ts — do not edit by hand.",
  "-- Regenerate with: npm run db:seed:export",
  "",
];

lines.push("-- elections");
for (const e of elections) {
  lines.push(
    `insert into elections (id, slug, name, kind, round_date, second_round_date, is_active) values (${uuid("election", e.slug)}, ${sqlString(e.slug)}, ${sqlString(e.name)}, ${sqlString(e.kind)}, ${sqlString(e.round_date)}, ${sqlString(e.second_round_date)}, ${sqlBool(e.is_active)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- parties");
for (const p of parties) {
  const key = p.id.replace("party-", "");
  lines.push(
    `insert into parties (id, name, short_name, orientation, color) values (${uuid("party", key)}, ${sqlString(p.name)}, ${sqlString(p.short_name)}, ${sqlString(p.orientation)}, ${sqlString(p.color)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- themes");
for (const t of themes) {
  lines.push(
    `insert into themes (id, slug, name, description, icon, order_index) values (${uuid("theme", t.slug)}, ${sqlString(t.slug)}, ${sqlString(t.name)}, ${sqlString(t.description)}, ${sqlString(t.icon)}, ${t.order_index}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidates");
for (const c of candidates) {
  const partyKey = c.party_id?.replace("party-", "");
  const electionSlug = elections.find((e) => e.id === c.election_id)?.slug ?? elections[0].slug;
  lines.push(
    `insert into candidates (id, slug, name, photo_url, party_id, biography, birth_date, birth_place, current_role, current_role_detail, official_website, election_id, is_demo, order_index) values (${uuid("candidate", c.slug)}, ${sqlString(c.slug)}, ${sqlString(c.name)}, ${sqlString(c.photo_url)}, ${partyKey ? uuid("party", partyKey) : "null"}, ${sqlString(c.biography)}, ${sqlString(c.birth_date ?? null)}, ${sqlString(c.birth_place ?? null)}, ${sqlString(c.current_role ?? null)}, ${sqlString(c.current_role_detail ?? null)}, ${sqlString(c.official_website)}, ${uuid("election", electionSlug)}, ${sqlBool(c.is_demo)}, ${c.order_index}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- questions");
for (const q of questions) {
  const themeSlug = q.theme_id.replace("theme-", "");
  lines.push(
    `insert into questions (id, theme_id, question, description, context, weight, answer_type, options, compatibility, order_index, is_active) values (${uuid("question", q.id)}, ${uuid("theme", themeSlug)}, ${sqlString(q.question)}, ${sqlString(q.description)}, ${sqlString(q.context)}, ${q.weight}, ${sqlString(q.answer_type)}, ${sqlJson(q.options)}, ${sqlJson(q.compatibility ?? null)}, ${q.order_index}, ${sqlBool(q.is_active)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidate_positions");
for (const pos of candidatePositions) {
  const candidate = candidates.find((c) => c.id === pos.candidate_id)!;
  lines.push(
    `insert into candidate_positions (id, candidate_id, question_id, answer_type, numeric_score, option_id, option_ids, explanation, source_url, source_name, verified_at) values (${uuid("position", pos.id)}, ${uuid("candidate", candidate.slug)}, ${uuid("question", pos.question_id)}, ${sqlString(pos.answer_type)}, ${sqlNumber(pos.numeric_score)}, ${sqlString(pos.option_id)}, ${sqlJson(pos.option_ids ?? null)}, ${sqlString(pos.explanation)}, ${sqlString(pos.source_url)}, ${sqlString(pos.source_name)}, ${sqlString(pos.verified_at)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- proposals");
for (const p of proposals) {
  const candidate = candidates.find((c) => c.id === p.candidate_id)!;
  const themeSlug = p.theme_id.replace("theme-", "");
  lines.push(
    `insert into proposals (id, candidate_id, theme_id, title, summary, description, source_name, source_url, published_at, verified_at, status, tags) values (${uuid("proposal", p.id)}, ${uuid("candidate", candidate.slug)}, ${uuid("theme", themeSlug)}, ${sqlString(p.title)}, ${sqlString(p.summary)}, ${sqlString(p.description)}, ${sqlString(p.source_name)}, ${sqlString(p.source_url)}, ${sqlString(p.published_at)}, ${sqlString(p.verified_at)}, ${sqlString(p.status)}, ${sqlString(p.tags)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- polls");
for (const poll of polls) {
  const electionSlug = elections.find((e) => e.id === poll.election_id)?.slug ?? elections[0].slug;
  lines.push(
    `insert into polls (id, election_id, institute, sponsor, field_start, field_end, sample_size, method, source_name, source_url, published_at, is_demo) values (${uuid("poll", poll.id)}, ${uuid("election", electionSlug)}, ${sqlString(poll.institute)}, ${sqlString(poll.sponsor)}, ${sqlString(poll.field_start)}, ${sqlString(poll.field_end)}, ${poll.sample_size}, ${sqlString(poll.method)}, ${sqlString(poll.source_name)}, ${sqlString(poll.source_url)}, ${sqlString(poll.published_at)}, ${sqlBool(poll.is_demo)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- poll_scenarios");
for (const s of pollScenarios) {
  lines.push(
    `insert into poll_scenarios (id, poll_id, label, round, order_index) values (${uuid("poll_scenario", s.id)}, ${uuid("poll", s.poll_id)}, ${sqlString(s.label)}, ${sqlString(s.round)}, ${s.order_index}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- poll_results");
for (const r of pollResults) {
  const candidate = candidates.find((c) => c.id === r.candidate_id)!;
  lines.push(
    `insert into poll_results (id, scenario_id, candidate_id, value, low, high) values (${uuid("poll_result", r.id)}, ${uuid("poll_scenario", r.scenario_id)}, ${uuid("candidate", candidate.slug)}, ${r.value}, ${sqlNumber(r.low)}, ${sqlNumber(r.high)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- measure_analyses (Passage au réel)");
for (const a of measureAnalyses) {
  lines.push(
    `insert into measure_analyses (id, proposal_id, status, summary, feasibility_status, precision_level, confidence_level, legal_path, legal_constitutional_change_required, legal_eu_change_required, legal_notes, legal_implementation_delay_min_months, legal_implementation_delay_max_months, implementation_existing_administration, implementation_new_recruitment_needed, implementation_notes, beneficiaries_groups, beneficiaries_description, beneficiaries_count_min, beneficiaries_count_central, beneficiaries_count_max, beneficiaries_source_name, beneficiaries_source_url, simulator_measure_id, reviewed_at, reviewed_by, published_at) values (${uuid("measure_analysis", a.id)}, ${uuid("proposal", a.proposal_id)}, ${sqlString(a.status)}, ${sqlString(a.summary)}, ${sqlString(a.feasibility_status)}, ${sqlString(a.precision_level)}, ${sqlString(a.confidence_level)}, ${sqlString(a.legal_path)}, ${sqlBool(a.legal_constitutional_change_required)}, ${sqlBool(a.legal_eu_change_required)}, ${sqlString(a.legal_notes)}, ${sqlNumber(a.legal_implementation_delay_min_months)}, ${sqlNumber(a.legal_implementation_delay_max_months)}, ${sqlString(a.implementation_existing_administration)}, ${sqlString(a.implementation_new_recruitment_needed)}, ${sqlString(a.implementation_notes)}, ${sqlJson(a.beneficiaries_groups)}, ${sqlString(a.beneficiaries_description)}, ${sqlNumber(a.beneficiaries_count_min)}, ${sqlNumber(a.beneficiaries_count_central)}, ${sqlNumber(a.beneficiaries_count_max)}, ${sqlString(a.beneficiaries_source_name)}, ${sqlString(a.beneficiaries_source_url)}, ${sqlString(a.simulator_measure_id)}, ${sqlString(a.reviewed_at)}, ${sqlString(a.reviewed_by)}, ${sqlString(a.published_at)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- measure_budget_estimates");
for (const b of measureBudgetEstimates) {
  lines.push(
    `insert into measure_budget_estimates (id, measure_analysis_id, source_type, source_name, source_url, annual_cost_min, annual_cost_central, annual_cost_max, annual_revenue_min, annual_revenue_central, annual_revenue_max, currency, reference_year, financing_identified, notes) values (${uuid("measure_budget_estimate", b.id)}, ${uuid("measure_analysis", b.measure_analysis_id)}, ${sqlString(b.source_type)}, ${sqlString(b.source_name)}, ${sqlString(b.source_url)}, ${sqlNumber(b.annual_cost_min)}, ${sqlNumber(b.annual_cost_central)}, ${sqlNumber(b.annual_cost_max)}, ${sqlNumber(b.annual_revenue_min)}, ${sqlNumber(b.annual_revenue_central)}, ${sqlNumber(b.annual_revenue_max)}, ${sqlString(b.currency)}, ${sqlNumber(b.reference_year)}, ${sqlString(b.financing_identified)}, ${sqlString(b.notes)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- measure_impacts");
for (const i of measureImpacts) {
  lines.push(
    `insert into measure_impacts (id, measure_analysis_id, impact_type, horizon, scenario, population, value_min, value_central, value_max, unit, confidence_level, method, source_name, source_url, scenario_assumptions, publication_date) values (${uuid("measure_impact", i.id)}, ${uuid("measure_analysis", i.measure_analysis_id)}, ${sqlString(i.impact_type)}, ${sqlString(i.horizon)}, ${sqlString(i.scenario)}, ${sqlString(i.population)}, ${sqlNumber(i.value_min)}, ${sqlNumber(i.value_central)}, ${sqlNumber(i.value_max)}, ${sqlString(i.unit)}, ${sqlString(i.confidence_level)}, ${sqlString(i.method)}, ${sqlString(i.source_name)}, ${sqlString(i.source_url)}, ${sqlString(i.scenario_assumptions)}, ${sqlString(i.publication_date)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- measure_assumptions");
for (const a of measureAssumptions) {
  lines.push(
    `insert into measure_assumptions (id, measure_analysis_id, name, value, unit, assumption_type, justification, source_name, source_url) values (${uuid("measure_assumption", a.id)}, ${uuid("measure_analysis", a.measure_analysis_id)}, ${sqlString(a.name)}, ${sqlString(a.value)}, ${sqlString(a.unit)}, ${sqlString(a.assumption_type)}, ${sqlString(a.justification)}, ${sqlString(a.source_name)}, ${sqlString(a.source_url)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidate_careers (Parcours & actes)");
for (const c of candidateCareers) {
  const candidate = candidates.find((cand) => cand.id === c.candidate_id)!;
  lines.push(
    `insert into candidate_careers (id, candidate_id, title, organization, sector, description, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values (${uuid("candidate_career", c.id)}, ${uuid("candidate", candidate.slug)}, ${sqlString(c.title)}, ${sqlString(c.organization)}, ${sqlString(c.sector)}, ${sqlString(c.description)}, ${sqlString(c.start_date)}, ${sqlString(c.end_date)}, ${sqlBool(c.is_ongoing)}, ${sqlString(c.source_name)}, ${sqlString(c.source_url)}, ${sqlString(c.source_type)}, ${sqlString(c.status)}, ${sqlString(c.verified_at)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidate_mandates");
for (const m of candidateMandates) {
  const candidate = candidates.find((cand) => cand.id === m.candidate_id)!;
  lines.push(
    `insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values (${uuid("candidate_mandate", m.id)}, ${uuid("candidate", candidate.slug)}, ${sqlString(m.title)}, ${sqlString(m.institution)}, ${sqlString(m.territory)}, ${sqlString(m.appointment_type)}, ${sqlString(m.party_at_time)}, ${sqlString(m.start_date)}, ${sqlString(m.end_date)}, ${sqlBool(m.is_ongoing)}, ${sqlString(m.source_name)}, ${sqlString(m.source_url)}, ${sqlString(m.source_type)}, ${sqlString(m.status)}, ${sqlString(m.verified_at)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidate_votes");
for (const v of candidateVotes) {
  const candidate = candidates.find((cand) => cand.id === v.candidate_id)!;
  const themeSlug = v.theme_id ? themes.find((t) => t.id === v.theme_id)?.slug : null;
  lines.push(
    `insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values (${uuid("candidate_vote", v.id)}, ${uuid("candidate", candidate.slug)}, ${sqlString(v.institution)}, ${sqlString(v.legislature)}, ${sqlString(v.official_vote_id)}, ${sqlString(v.title)}, ${sqlString(v.description)}, ${themeSlug ? uuid("theme", themeSlug) : "null"}, ${sqlString(v.vote_date)}, ${sqlString(v.candidate_vote)}, ${sqlString(v.importance_level)}, ${sqlBool(v.featured)}, ${sqlString(v.source_name)}, ${sqlString(v.source_url)}, ${sqlString(v.source_type)}, ${sqlString(v.status)}, ${sqlString(v.verified_at)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidate_position_history");
for (const h of candidatePositionHistory) {
  const candidate = candidates.find((cand) => cand.id === h.candidate_id)!;
  const themeSlug = h.theme_id ? themes.find((t) => t.id === h.theme_id)?.slug : null;
  lines.push(
    `insert into candidate_position_history (id, candidate_id, theme_id, subject, position_summary, quote, date, source_name, source_url, source_type, status, verified_at) values (${uuid("candidate_position_history", h.id)}, ${uuid("candidate", candidate.slug)}, ${themeSlug ? uuid("theme", themeSlug) : "null"}, ${sqlString(h.subject)}, ${sqlString(h.position_summary)}, ${sqlString(h.quote)}, ${sqlString(h.date)}, ${sqlString(h.source_name)}, ${sqlString(h.source_url)}, ${sqlString(h.source_type)}, ${sqlString(h.status)}, ${sqlString(h.verified_at)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidate_position_evolutions");
for (const e of candidatePositionEvolutions) {
  const candidate = candidates.find((cand) => cand.id === e.candidate_id)!;
  const themeSlug = e.theme_id ? themes.find((t) => t.id === e.theme_id)?.slug : null;
  lines.push(
    `insert into candidate_position_evolutions (id, candidate_id, theme_id, subject, evolution_type, confidence, summary, candidate_explanation, candidate_explanation_source_url, status, verified_at) values (${uuid("candidate_position_evolution", e.id)}, ${uuid("candidate", candidate.slug)}, ${themeSlug ? uuid("theme", themeSlug) : "null"}, ${sqlString(e.subject)}, ${sqlString(e.evolution_type)}, ${sqlString(e.confidence)}, ${sqlString(e.summary)}, ${sqlString(e.candidate_explanation)}, ${sqlString(e.candidate_explanation_source_url)}, ${sqlString(e.status)}, ${sqlString(e.verified_at)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidate_legal_cases");
for (const l of candidateLegalCases) {
  const candidate = candidates.find((cand) => cand.id === l.candidate_id)!;
  lines.push(
    `insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values (${uuid("candidate_legal_case", l.id)}, ${uuid("candidate", candidate.slug)}, ${sqlString(l.title)}, ${sqlString(l.case_type)}, ${sqlString(l.summary)}, ${sqlString(l.legal_status)}, ${sqlString(l.jurisdiction)}, ${sqlString(l.start_date)}, ${sqlString(l.decision_date)}, ${sqlString(l.last_updated)}, ${sqlString(l.next_review_at)}, ${sqlString(l.source_name)}, ${sqlString(l.source_url)}, ${sqlString(l.source_type)}, ${sqlString(l.status)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidate_controversies");
for (const c of candidateControversies) {
  const candidate = candidates.find((cand) => cand.id === c.candidate_id)!;
  lines.push(
    `insert into candidate_controversies (id, candidate_id, title, summary, event_date, context, candidate_response, candidate_response_source_url, controversy_status, last_updated, next_review_at, source_name, source_url, source_type, status) values (${uuid("candidate_controversy", c.id)}, ${uuid("candidate", candidate.slug)}, ${sqlString(c.title)}, ${sqlString(c.summary)}, ${sqlString(c.event_date)}, ${sqlString(c.context)}, ${sqlString(c.candidate_response)}, ${sqlString(c.candidate_response_source_url)}, ${sqlString(c.controversy_status)}, ${sqlString(c.last_updated)}, ${sqlString(c.next_review_at)}, ${sqlString(c.source_name)}, ${sqlString(c.source_url)}, ${sqlString(c.source_type)}, ${sqlString(c.status)}) on conflict (id) do nothing;`
  );
}

lines.push("", "-- candidate_transparency_records");
for (const t of candidateTransparencyRecords) {
  const candidate = candidates.find((cand) => cand.id === t.candidate_id)!;
  lines.push(
    `insert into candidate_transparency_records (id, candidate_id, record_type, title, publication_date, source_name, source_url, source_type, status, verified_at) values (${uuid("candidate_transparency_record", t.id)}, ${uuid("candidate", candidate.slug)}, ${sqlString(t.record_type)}, ${sqlString(t.title)}, ${sqlString(t.publication_date)}, ${sqlString(t.source_name)}, ${sqlString(t.source_url)}, ${sqlString(t.source_type)}, ${sqlString(t.status)}, ${sqlString(t.verified_at)}) on conflict (id) do nothing;`
  );
}

const outPath = join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(outPath, lines.join("\n") + "\n", "utf-8");
console.log(`Wrote ${outPath}`);
