-- Ajoute le sondage Ipsos bva CESI / Le Parisien de septembre 2026 (hypothèse
-- R. Glucksmann et E. Philippe), déjà présent dans src/lib/data/local/polls.ts.
-- Table polls/poll_scenarios/poll_results déjà créées par 0002/0003 — un
-- simple insert suffit, généré via npm run db:seed:export.

insert into polls (id, election_id, institute, sponsor, field_start, field_end, sample_size, method, source_name, source_url, published_at, is_demo) values (uuid_generate_v5(uuid_ns_url(), 'poliscope:poll:poll-ipsos-bva-le-parisien-2026-09'), uuid_generate_v5(uuid_ns_url(), 'poliscope:election:presidentielle-2027'), 'Ipsos bva CESI école d''ingénieurs', 'Le Parisien', '2026-08-31', '2026-09-02', 1500, 'Échantillon interrogé en ligne (Access panel Ipsos), représentatif de la population française de 18 ans et plus inscrite sur les listes électorales, selon la méthode des quotas (sexe, âge, profession, catégorie d''agglomération, région). Base pour cette hypothèse : 1 005 personnes certaines d''aller voter et exprimées.', 'Ipsos — Notice technique Commission des sondages', 'https://www.commission-des-sondages.fr/notices/files/notices/2026/septembre/10250-pres-iv-ipsos-bva-le-parisien-5-septembre.pdf', '2026-09-05', false) on conflict (id) do nothing;
insert into poll_scenarios (id, poll_id, label, round, order_index) values (uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_scenario:poll-scenario-ipsos-2026-09-glucksmann-philippe'), uuid_generate_v5(uuid_ns_url(), 'poliscope:poll:poll-ipsos-bva-le-parisien-2026-09'), 'Hypothèse R. Glucksmann et E. Philippe', 'premier_tour', 0) on conflict (id) do nothing;
insert into poll_results (id, scenario_id, candidate_id, value, low, high) values (uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_result:poll-result-ipsos-2026-09-gp-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_scenario:poll-scenario-ipsos-2026-09-glucksmann-philippe'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 34.5, 31.6, 37.4) on conflict (id) do nothing;
insert into poll_results (id, scenario_id, candidate_id, value, low, high) values (uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_result:poll-result-ipsos-2026-09-gp-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_scenario:poll-scenario-ipsos-2026-09-glucksmann-philippe'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 19, 16.6, 21.4) on conflict (id) do nothing;
insert into poll_results (id, scenario_id, candidate_id, value, low, high) values (uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_result:poll-result-ipsos-2026-09-gp-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_scenario:poll-scenario-ipsos-2026-09-glucksmann-philippe'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 15, 12.8, 17.2) on conflict (id) do nothing;
insert into poll_results (id, scenario_id, candidate_id, value, low, high) values (uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_result:poll-result-ipsos-2026-09-gp-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_scenario:poll-scenario-ipsos-2026-09-glucksmann-philippe'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:raphael-glucksmann'), 12, 10, 14) on conflict (id) do nothing;
insert into poll_results (id, scenario_id, candidate_id, value, low, high) values (uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_result:poll-result-ipsos-2026-09-gp-5'), uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_scenario:poll-scenario-ipsos-2026-09-glucksmann-philippe'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 7.5, 5.9, 9.1) on conflict (id) do nothing;
insert into poll_results (id, scenario_id, candidate_id, value, low, high) values (uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_result:poll-result-ipsos-2026-09-gp-6'), uuid_generate_v5(uuid_ns_url(), 'poliscope:poll_scenario:poll-scenario-ipsos-2026-09-glucksmann-philippe'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-tondelier'), 4, 2.8, 5.2) on conflict (id) do nothing;
