-- "Parcours & actes" — premières données vérifiées : affaires judiciaires,
-- une controverse documentée, et quelques votes parlementaires majeurs à
-- l'Assemblée nationale. Recherchées et recoupées individuellement contre
-- des sources identifiables en septembre 2026 (voir chaque source_url) —
-- mêmes faits que src/lib/data/local/candidate-records.ts, avec lequel ce
-- fichier doit rester synchronisé à la main (ces tables ne sont pas
-- couvertes par scripts/export-seed.ts, réservé au jeu de démonstration).
--
-- Toutes les lignes sont insérées avec status = 'published' : chaque fait a
-- été vérifié contre au moins une source nommée avant d'être ajouté ici. Ce
-- n'est pas une recherche exhaustive — voir /methodologie : une rubrique
-- vide (candidat non listé ci-dessous) signifie "non documenté dans
-- Polysia", jamais "aucune affaire".
--
-- Idempotent : chaque ligne a un identifiant déterministe
-- (uuid_generate_v5), donc rejouer cette migration ne duplique rien.

-- ---------------------------------------------------------------------------
-- candidate_votes
-- ---------------------------------------------------------------------------

-- Scrutin n°519 (17e législature) — motion de censure contre le gouvernement
-- Michel Barnier, déposée après l'engagement de sa responsabilité (49.3) sur
-- le PLFSS 2025. Adoptée le 4 décembre 2024 avec 331 voix, elle a renversé
-- le gouvernement. Source : Assemblée nationale (analyse officielle du scrutin).
insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_vote:519-marine-le-pen'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'assemblee_nationale', '17e législature', '519', 'Motion de censure contre le gouvernement Michel Barnier', 'Motion déposée par les groupes du Nouveau Front populaire après l''engagement de la responsabilité du gouvernement (article 49, alinéa 3) sur le projet de loi de financement de la Sécurité sociale pour 2025. Son adoption entraîne la démission du gouvernement.', null, '2024-12-04', 'for', 'major', true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/17/scrutins/519', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_vote:519-francois-ruffin'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:francois-ruffin'), 'assemblee_nationale', '17e législature', '519', 'Motion de censure contre le gouvernement Michel Barnier', 'Motion déposée par les groupes du Nouveau Front populaire après l''engagement de la responsabilité du gouvernement (article 49, alinéa 3) sur le projet de loi de financement de la Sécurité sociale pour 2025. Son adoption entraîne la démission du gouvernement.', null, '2024-12-04', 'for', 'major', true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/17/scrutins/519', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;

-- Scrutin n°3213 (16e législature) — adoption définitive du projet de loi
-- "pour contrôler l'immigration, améliorer l'intégration" (texte de la
-- commission mixte paritaire), le 19 décembre 2023.
insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_vote:3213-marine-le-pen'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'assemblee_nationale', '16e législature', '3213', 'Adoption de la loi « pour contrôler l''immigration, améliorer l''intégration »', 'Vote sur l''ensemble du texte issu de la commission mixte paritaire, après son rejet en première lecture le 11 décembre 2023. Texte durci par rapport à la version initiale du gouvernement.', uuid_generate_v5(uuid_ns_url(), 'poliscope:theme:immigration'), '2023-12-19', 'for', 'major', true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/16/scrutins/3213', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_vote:3213-francois-ruffin'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:francois-ruffin'), 'assemblee_nationale', '16e législature', '3213', 'Adoption de la loi « pour contrôler l''immigration, améliorer l''intégration »', 'Vote sur l''ensemble du texte issu de la commission mixte paritaire, après son rejet en première lecture le 11 décembre 2023. Texte durci par rapport à la version initiale du gouvernement.', uuid_generate_v5(uuid_ns_url(), 'poliscope:theme:immigration'), '2023-12-19', 'against', 'major', true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/16/scrutins/3213', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_vote:3213-nicolas-dupont-aignan'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nicolas-dupont-aignan'), 'assemblee_nationale', '16e législature', '3213', 'Adoption de la loi « pour contrôler l''immigration, améliorer l''intégration »', 'Vote sur l''ensemble du texte issu de la commission mixte paritaire, après son rejet en première lecture le 11 décembre 2023. Texte durci par rapport à la version initiale du gouvernement.', uuid_generate_v5(uuid_ns_url(), 'poliscope:theme:immigration'), '2023-12-19', 'abstention', 'major', true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/16/scrutins/3213', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_vote:3213-fabien-roussel'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:fabien-roussel'), 'assemblee_nationale', '16e législature', '3213', 'Adoption de la loi « pour contrôler l''immigration, améliorer l''intégration »', 'Vote sur l''ensemble du texte issu de la commission mixte paritaire, après son rejet en première lecture le 11 décembre 2023. Texte durci par rapport à la version initiale du gouvernement.', uuid_generate_v5(uuid_ns_url(), 'poliscope:theme:immigration'), '2023-12-19', 'against', 'major', true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/16/scrutins/3213', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- candidate_legal_cases
-- ---------------------------------------------------------------------------

insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_legal_case:marine-le-pen-assistants-rn'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Affaire des assistants parlementaires du RN au Parlement européen', 'Détournement de fonds publics', 'Marine Le Pen a été condamnée le 31 mars 2025 par le tribunal correctionnel de Paris à 4 ans de prison (dont 2 ans aménageables sous surveillance électronique, 2 ans avec sursis), 100 000 € d''amende et 5 ans d''inéligibilité exécutoire immédiatement, pour détournement de fonds publics dans l''affaire des emplois d''assistants parlementaires du Front national/Rassemblement national au Parlement européen (faits visés : 2004-2016). En appel, la cour d''appel de Paris l''a condamnée à nouveau le 7 juillet 2026, avec une peine réduite : 3 ans de prison (dont 1 an ferme aménageable sous bracelet électronique, 2 ans avec sursis), 100 000 € d''amende et 45 mois d''inéligibilité (dont 30 mois avec sursis). Elle a annoncé se pourvoir en cassation.', 'convicted_on_appeal', 'Cour d''appel de Paris', null, '2026-07-07', '2026-09-10', null, 'Toute l''Europe', 'https://www.touteleurope.eu/vie-politique-des-etats-membres/proces-des-assistants-du-rn-marine-le-pen-condamnee-en-appel-mais-eligible-a-l-election-presidentielle-2027/', 'media', 'published')
  on conflict (id) do nothing;

insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_legal_case:melenchon-perquisition-lfi'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Perquisition houleuse au siège de La France insoumise (2018)', 'Intimidation envers un magistrat et un dépositaire de l''autorité publique, rébellion, provocation', 'Le 16 octobre 2018, lors d''une perquisition au siège de La France insoumise et à son domicile menée dans le cadre d''enquêtes sur des emplois présumés fictifs d''assistants parlementaires européens et sur les comptes de campagne de 2017, Jean-Luc Mélenchon a bousculé des représentants du parquet et forcé le passage. Il a été condamné le 9 décembre 2019 par le tribunal correctionnel de Bobigny à trois mois de prison avec sursis et 8 000 € d''amende. Il a annoncé publiquement ne pas faire appel.', 'convicted_final', 'Tribunal correctionnel de Bobigny', '2018-10-16', '2019-12-09', '2026-09-10', null, 'Franceinfo', 'https://www.franceinfo.fr/politique/melenchon/perquisition-mouvementee-a-la-france-insoumise-jean-luc-melenchon-condamne-a-trois-mois-de-prison-avec-sursis-et-8-000-euros-d-amende_3737089.html', 'media', 'published')
  on conflict (id) do nothing;

insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_legal_case:melenchon-assistants-lfi-pe'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Enquête sur les assistants parlementaires de La France insoumise au Parlement européen', 'Soupçon d''emploi fictif d''assistants parlementaires', 'Jean-Luc Mélenchon et d''anciens assistants parlementaires étaient visés, depuis un signalement de l''Office européen de lutte antifraude (OLAF) en 2017 puis une enquête judiciaire française ouverte en 2018, par des soupçons d''avoir employé des assistants du Parlement européen pour soutenir principalement son activité politique nationale — un mécanisme similaire à celui jugé dans l''affaire visant le Rassemblement national. Après huit ans d''instruction, les juges ont clos le dossier le 26 mai 2026 sans mise en examen de Jean-Luc Mélenchon. Deux anciens assistants restent sous statut de témoin assisté.', 'closed_without_action', null, null, '2026-05-26', '2026-09-10', null, 'Franceinfo', 'https://www.franceinfo.fr/politique/la-france-insoumise/enquete-sur-les-assistants-parlementaires-de-lfi-l-instruction-est-close-sans-mise-en-examen_8029814.html', 'media', 'published')
  on conflict (id) do nothing;

insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_legal_case:bertrand-diffamation-mediapart'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Diffamation envers Mediapart', 'Diffamation', 'Le 6 juillet 2010, en marge d''un meeting au Raincy, Xavier Bertrand, alors secrétaire général de l''UMP, avait accusé le site Mediapart d''utiliser des « méthodes fascisantes » à propos de ses révélations dans l''affaire Bettencourt. Mediapart avait porté plainte pour diffamation. Le tribunal correctionnel de Paris l''a relaxé le 26 mars 2013, jugeant que ses propos ne visaient pas un fait précis. Mediapart avait indiqué vouloir poursuivre le débat judiciaire ; Polysia n''a pas trouvé de confirmation sourcée d''une décision d''appel.', 'acquitted', 'Tribunal correctionnel de Paris', null, '2013-03-26', '2026-09-10', null, 'Le Nouvelliste', 'https://www.lenouvelliste.ch/monde/xavier-bertrand-relaxe-des-poursuites-de-mediapart-264658', 'media', 'published')
  on conflict (id) do nothing;

insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_legal_case:philippe-covid-cjr'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 'Mise en cause pour la gestion de la crise du Covid-19', 'Mise en cause devant la Cour de justice de la République', 'Une information judiciaire a été ouverte en 2020 devant la Cour de justice de la République (CJR), seule juridiction compétente pour juger les membres du gouvernement pour des actes commis dans l''exercice de leurs fonctions, visant notamment l''ancien Premier ministre Édouard Philippe pour « mise en danger de la vie d''autrui » et « abstention volontaire de combattre un sinistre » dans la gestion de la crise sanitaire. Entendu en octobre 2022, il a été placé sous le statut de témoin assisté, sans mise en examen. La CJR a prononcé un non-lieu à son égard le 7 juillet 2025.', 'dismissed', 'Cour de justice de la République', null, '2025-07-07', '2026-09-10', null, 'Le Club des Juristes', 'https://www.leclubdesjuristes.com/en-bref/gestion-du-covid-19-la-cjr-prononce-un-non-lieu-a-lencontre-de-edouard-philippe-agnes-buzyn-et-olivier-veran-11443/', 'media', 'published')
  on conflict (id) do nothing;

insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_legal_case:dupont-aignan-invasion-migratoire'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nicolas-dupont-aignan'), 'Propos sur l''« invasion migratoire » (tweet de 2017)', 'Provocation à la haine ou à la discrimination', 'Après un tweet du 17 janvier 2017 évoquant une « invasion migratoire », la Licra avait porté plainte contre Nicolas Dupont-Aignan pour provocation à la haine ou à la discrimination. Le tribunal de Paris (17e chambre correctionnelle) l''a relaxé le 6 juin 2018, estimant que l''infraction n''était pas caractérisée ; ses avocats invoquaient par ailleurs l''immunité parlementaire, argument que le tribunal n''a pas retenu.', 'acquitted', 'Tribunal de Paris (17e chambre correctionnelle)', null, '2018-06-06', '2026-09-10', null, 'Public Sénat', 'https://www.publicsenat.fr/actualites/politique/dupont-aignan-relaxe-pour-ses-propos-sur-l-invasion-migratoire-en-france-86680', 'media', 'published')
  on conflict (id) do nothing;

insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_legal_case:roussel-diffamation-rn'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:fabien-roussel'), 'Poursuites du Rassemblement national pour diffamation', 'Diffamation (poursuites engagées par le Rassemblement national)', 'En octobre 2019, après avoir mis en cause l''implication de militants d''extrême droite dans des actions violentes, dont l''attaque de la mosquée de Bayonne, sur le plateau des « 4 vérités » (France 2), Fabien Roussel a été poursuivi pour diffamation par le Rassemblement national devant le tribunal correctionnel de Paris. Il a été relaxé le 27 janvier 2022, le tribunal retenant l''excuse de bonne foi. La cour d''appel de Paris a confirmé cette relaxe le 15 décembre 2022 et débouté le RN de l''ensemble de ses demandes.', 'acquitted', 'Cour d''appel de Paris', null, '2022-12-15', '2026-09-10', null, 'PCF (compte-rendu de la décision)', 'https://www.pcf.fr/le_rassemblement_national_d_bout_de_son_action_en_justice_contre_fabien_roussel', 'candidate', 'published')
  on conflict (id) do nothing;

insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_legal_case:roussel-emploi-fictif'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:fabien-roussel'), 'Soupçon d''emploi fictif comme assistant parlementaire', 'Soupçon d''emploi fictif d''assistant parlementaire', 'Selon Mediapart, Fabien Roussel aurait occupé un emploi fictif d''assistant parlementaire auprès du député Jean-Jacques Candelier entre 2009 et 2014, pour un salaire mensuel de 3 000 €. Il conteste les accusations, affirmant avoir réellement suivi les dossiers du Douaisis pour ce mandat. Le Parquet national financier a ouvert une enquête préliminaire en mars 2022 ; elle était toujours en cours à la dernière vérification publique de ce dossier (21 février 2026), sans mise en examen ni décision de justice à ce stade.', 'investigation', 'Parquet national financier', null, null, '2026-09-10', null, 'Poligraph', 'https://poligraph.fr/affaires/fabien-roussel-soupcons-d-emploi-fictif-comme-assistant-parlementaire', 'media', 'published')
  on conflict (id) do nothing;

insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_legal_case:ruffin-diffamation-quartier-nord'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:francois-ruffin'), 'Diffamation envers un habitant d''Amiens Nord (livre « Quartier Nord »)', 'Diffamation', 'Dans son livre « Quartier Nord » (2006), François Ruffin avait désigné sous un pseudonyme un habitant du quartier, Nourédine Gaham, avec des formules dégradantes et des accusations non étayées. Ce dernier a porté plainte pour diffamation ; le tribunal correctionnel d''Amiens a condamné François Ruffin le 23 avril 2008. Polysia n''a pas trouvé de source confirmant un appel de cette décision.', 'convicted_final', 'Tribunal correctionnel d''Amiens', null, '2008-04-23', '2026-09-10', null, 'Franceinfo', 'https://www.franceinfo.fr/societe/nuit-debout/journalisme-engage-critique-des-medias-et-france-peripherique-qui-est-francois-ruffin-l-inspirateur-de-nuit-debout_1413979.html', 'media', 'published')
  on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- candidate_controversies
-- ---------------------------------------------------------------------------

insert into candidate_controversies (id, candidate_id, title, summary, event_date, context, candidate_response, candidate_response_source_url, controversy_status, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_controversy:dupont-aignan-fraude-scrutin'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nicolas-dupont-aignan'), 'Sanctionné par l''Assemblée nationale pour avoir voté à la place d''un collègue absent', 'Lors d''un vote sur un projet de loi relatif à la gestion de la crise sanitaire, fin juillet 2021, Nicolas Dupont-Aignan a voté depuis le boîtier de son collègue José Évrard, absent. Le Bureau de l''Assemblée nationale l''a sanctionné le 13 octobre 2021 pour « fraude au scrutin » : rappel au règlement et retrait d''un quart de son indemnité parlementaire pour un mois.', '2021-10-13', 'Nicolas Dupont-Aignan a récusé le terme de « fraude », évoquant une « erreur » et un « quiproquo administratif » : il affirme avoir reçu une délégation de vote de José Évrard, mais qu''un document nécessaire à la procédure n''aurait pas été transmis à temps.', null, null, 'disputed', '2026-09-10', null, 'LCP — Assemblée nationale', 'https://lcp.fr/actualites/nicolas-dupont-aignan-sanctionne-par-l-assemblee-le-depute-recuse-la-fraude-et-concede', 'media', 'published')
  on conflict (id) do nothing;
