-- "Parcours & actes" — mandats politiques. Historique de carrière recherché
-- et recoupé individuellement contre des sources identifiables (Assemblée
-- nationale, Sénat, Parlement européen quand disponibles, Wikipédia sinon —
-- voir chaque source_url / source_type) en septembre 2026. Mêmes faits que
-- src/lib/data/local/candidate-records.ts, avec lequel ce fichier doit
-- rester synchronisé à la main.
--
-- Ce n'est pas une recherche exhaustive de chaque mandat local mineur —
-- voir /methodologie : un candidat non listé, ou une période non listée,
-- signifie "non documenté dans Polysia", jamais "aucun mandat".
--
-- Idempotent : chaque ligne a un identifiant déterministe
-- (uuid_generate_v5), donc rejouer cette migration ne duplique rien.

insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Conseiller général', 'Conseil général de l''Essonne', 'Canton de Massy-Ouest', 'elu', 'Parti socialiste', '1985-03-23', '1992-04-02', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Jean-Luc_M%C3%A9lenchon', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Adjoint au maire de Massy', 'Mairie de Massy', null, 'elu', 'Parti socialiste', '1989-03-20', '1995-06-11', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Jean-Luc_M%C3%A9lenchon', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Sénateur', 'Sénat', 'Essonne', 'elu', 'Parti socialiste', '1986-10-02', '2000-04-27', false, 'Sénat', 'https://www.senat.fr/senateur/melenchon_jean_luc86039k.html', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Conseiller général', 'Conseil général de l''Essonne', 'Canton de Massy-Ouest', 'elu', 'Parti socialiste', '1998-03-23', '2004-04-02', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Jean-Luc_M%C3%A9lenchon', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-5'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Président délégué du conseil général de l''Essonne', 'Conseil général de l''Essonne', null, 'elu', 'Parti socialiste', '1998-03-23', '2004-04-02', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Jean-Luc_M%C3%A9lenchon', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-6'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Ministre délégué à l''Enseignement professionnel', 'Gouvernement (Jospin)', null, 'nomme', 'Parti socialiste', '2000-03-27', '2002-05-06', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Jean-Luc_M%C3%A9lenchon', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-7'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Sénateur', 'Sénat', 'Essonne', 'elu', 'Parti socialiste', '2004-10-01', '2010-01-07', false, 'Sénat', 'https://www.senat.fr/senateur/melenchon_jean_luc86039k.html', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-8'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Coprésident du Parti de Gauche', 'Parti de Gauche', null, 'elu', 'Parti de Gauche', '2009-02-01', '2014-08-22', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Jean-Luc_M%C3%A9lenchon', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-9'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Député européen', 'Parlement européen', null, 'elu', 'Parti de Gauche', '2009-07-14', '2017-06-18', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Jean-Luc_M%C3%A9lenchon', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-10'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Président du groupe La France insoumise', 'Assemblée nationale', null, 'elu', 'La France insoumise', '2017-06-27', '2021-10-12', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Jean-Luc_M%C3%A9lenchon', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:jean-luc-melenchon-11'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Député', 'Assemblée nationale', 'Bouches-du-Rhône (4e circonscription)', 'elu', 'La France insoumise', '2017-06-21', '2022-06-21', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Jean-Luc_M%C3%A9lenchon', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-le-pen-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Conseillère régionale', 'Conseil régional', 'Nord-Pas-de-Calais', 'elu', 'Front national', '1998-03-21', '2004-03-28', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Marine_Le_Pen', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-le-pen-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Conseillère régionale', 'Conseil régional', 'Île-de-France', 'elu', 'Front national', '2004-03-28', '2010-03-21', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Marine_Le_Pen', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-le-pen-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Députée européenne', 'Parlement européen', null, 'elu', 'Front national', '2004-07-20', '2017-06-18', false, 'Parlement européen', 'https://www.europarl.europa.eu/meps/fr/28210/MARINE_LE+PEN/history/8', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-le-pen-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Conseillère régionale', 'Conseil régional', 'Nord-Pas-de-Calais puis Hauts-de-France', 'elu', 'Front national puis Rassemblement national', '2010-03-26', '2021-07-02', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Marine_Le_Pen', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-le-pen-5'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Présidente du Front national (Rassemblement national à partir de 2018)', 'Front national / Rassemblement national', null, 'elu', null, '2011-01-16', '2021-09-13', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Marine_Le_Pen', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-le-pen-6'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Députée', 'Assemblée nationale', 'Pas-de-Calais (11e circonscription)', 'elu', 'Front national puis Rassemblement national', '2017-06-21', null, true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/deputes/PA720614/fonctions', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-le-pen-7'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Conseillère départementale', 'Conseil départemental du Pas-de-Calais', 'Canton d''Hénin-Beaumont-2', 'elu', 'Rassemblement national', '2021-07-11', '2025-11-10', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Marine_Le_Pen', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-le-pen-8'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Présidente du groupe Rassemblement National', 'Assemblée nationale', null, 'elu', 'Rassemblement national', '2022-06-29', '2024-06-09', false, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/deputes/PA720614/fonctions?archive=oui', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-le-pen-9'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Présidente du groupe Rassemblement National', 'Assemblée nationale', null, 'elu', 'Rassemblement national', '2024-07-19', null, true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/deputes/PA720614/fonctions', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:edouard-philippe-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 'Conseiller régional', 'Conseil régional', 'Haute-Normandie', 'elu', 'UMP', '2004-04-02', '2008-03-18', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/%C3%89douard_Philippe', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:edouard-philippe-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 'Conseiller général', 'Conseil général', 'Canton du Havre-5', 'elu', 'UMP', '2008-03-16', '2012-04-22', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/%C3%89douard_Philippe', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:edouard-philippe-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 'Maire du Havre', 'Mairie du Havre', null, 'elu', 'UMP', '2010-10-24', '2017-05-20', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/%C3%89douard_Philippe', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:edouard-philippe-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 'Président de la communauté de l''agglomération havraise', 'Communauté de l''agglomération havraise', null, 'elu', 'UMP', '2010-12-18', '2017-06-25', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/%C3%89douard_Philippe', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:edouard-philippe-5'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 'Député', 'Assemblée nationale', 'Seine-Maritime (7e circonscription)', 'elu', 'Les Républicains', '2012-03-24', '2017-06-15', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/%C3%89douard_Philippe', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:edouard-philippe-6'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 'Premier ministre', 'Gouvernement', null, 'nomme', null, '2017-05-15', '2020-07-03', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/%C3%89douard_Philippe', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:edouard-philippe-7'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 'Maire du Havre', 'Mairie du Havre', null, 'elu', 'Horizons', '2020-07-05', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/%C3%89douard_Philippe', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:edouard-philippe-8'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 'Président du Havre Seine Métropole', 'Havre Seine Métropole', null, 'elu', 'Horizons', '2020-07-15', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/%C3%89douard_Philippe', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:edouard-philippe-9'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:edouard-philippe'), 'Président d''Horizons', 'Horizons', null, 'elu', null, '2021-10-09', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/%C3%89douard_Philippe', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Député', 'Assemblée nationale', 'Aisne (2e circonscription)', 'elu', 'UMP', '2002-06-19', '2004-04-30', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Secrétaire d''État chargé de l''Assurance maladie', 'Gouvernement', null, 'nomme', null, '2004-03-31', '2005-05-31', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Ministre de la Santé et des Solidarités', 'Gouvernement', null, 'nomme', null, '2005-06-02', '2007-03-26', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Député', 'Assemblée nationale', 'Aisne (2e circonscription)', 'elu', 'UMP', '2007-06-20', '2007-07-19', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-5'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Ministre du Travail', 'Gouvernement', null, 'nomme', null, '2007-05-18', '2009-01-15', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-6'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Secrétaire général de l''UMP', 'UMP', null, 'nomme', 'UMP', '2009-01-24', '2010-11-17', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-7'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Député', 'Assemblée nationale', 'Aisne (2e circonscription)', 'elu', 'UMP', '2009-02-15', '2010-12-14', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-8'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Ministre du Travail, de l''Emploi et de la Santé', 'Gouvernement', null, 'nomme', null, '2010-11-14', '2012-05-10', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-9'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Maire de Saint-Quentin', 'Mairie de Saint-Quentin', null, 'elu', 'UMP', '2010-10-04', '2016-01-14', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-10'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Député', 'Assemblée nationale', 'Aisne (2e circonscription)', 'elu', 'UMP puis Les Républicains', '2012-06-20', '2016-01-14', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:xavier-bertrand-11'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:xavier-bertrand'), 'Président du conseil régional des Hauts-de-France', 'Conseil régional des Hauts-de-France', null, 'elu', 'Sans étiquette', '2016-01-04', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Xavier_Bertrand', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:bruno-retailleau-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 'Député', 'Assemblée nationale', 'Vendée', 'elu', 'RPR', '1994-11-27', '1997-04-21', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Bruno_Retailleau', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:bruno-retailleau-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 'Vice-président du conseil régional des Pays de la Loire', 'Conseil régional des Pays de la Loire', null, 'elu', 'RPR', '1998-03-28', '2004-04-02', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Bruno_Retailleau', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:bruno-retailleau-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 'Sénateur', 'Sénat', 'Vendée', 'elu', 'UMP', '2004-10-01', '2024-10-20', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Bruno_Retailleau', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:bruno-retailleau-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 'Président du conseil général de la Vendée', 'Conseil général de la Vendée', null, 'elu', 'UMP', '2010-10-31', '2015-04-01', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Bruno_Retailleau', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:bruno-retailleau-5'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 'Président du groupe UMP puis Les Républicains', 'Sénat', null, 'elu', 'UMP puis Les Républicains', '2014-10-07', '2024-09-30', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Bruno_Retailleau', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:bruno-retailleau-6'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 'Président du conseil régional des Pays de la Loire', 'Conseil régional des Pays de la Loire', null, 'elu', 'Les Républicains', '2016-01-04', '2017-09-30', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Bruno_Retailleau', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:bruno-retailleau-7'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 'Ministre de l''Intérieur', 'Gouvernement', null, 'nomme', null, '2024-09-21', '2025-10-12', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Bruno_Retailleau', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:bruno-retailleau-8'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 'Sénateur', 'Sénat', 'Vendée', 'elu', 'Les Républicains', '2025-11-13', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Bruno_Retailleau', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:bruno-retailleau-9'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 'Président des Républicains', 'Les Républicains', null, 'elu', null, '2025-05-18', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Bruno_Retailleau', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:gabriel-attal-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:gabriel-attal'), 'Député', 'Assemblée nationale', 'Hauts-de-Seine (10e circonscription)', 'elu', 'La République en marche', '2017-06-21', '2018-11-16', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Gabriel_Attal', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:gabriel-attal-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:gabriel-attal'), 'Porte-parole de La République en marche', 'La République en marche', null, 'nomme', 'La République en marche', '2018-01-04', '2018-10-16', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Gabriel_Attal', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:gabriel-attal-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:gabriel-attal'), 'Secrétaire d''État auprès du ministre de l''Éducation nationale', 'Gouvernement', null, 'nomme', null, '2018-10-16', '2020-07-06', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Gabriel_Attal', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:gabriel-attal-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:gabriel-attal'), 'Secrétaire d''État, porte-parole du gouvernement', 'Gouvernement', null, 'nomme', null, '2020-07-06', '2022-05-20', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Gabriel_Attal', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:gabriel-attal-5'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:gabriel-attal'), 'Député', 'Assemblée nationale', 'Hauts-de-Seine (10e circonscription)', 'elu', 'Renaissance', '2022-06-22', '2022-07-22', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Gabriel_Attal', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:gabriel-attal-6'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:gabriel-attal'), 'Ministre délégué chargé des Comptes publics', 'Gouvernement', null, 'nomme', null, '2022-05-20', '2023-07-20', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Gabriel_Attal', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:gabriel-attal-7'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:gabriel-attal'), 'Ministre de l''Éducation nationale et de la Jeunesse', 'Gouvernement', null, 'nomme', null, '2023-07-20', '2024-01-11', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Gabriel_Attal', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:gabriel-attal-8'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:gabriel-attal'), 'Premier ministre', 'Gouvernement', null, 'nomme', null, '2024-01-09', '2024-09-05', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Gabriel_Attal', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:gabriel-attal-9'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:gabriel-attal'), 'Député', 'Assemblée nationale', 'Hauts-de-Seine (10e circonscription)', 'elu', 'Renaissance', '2024-07-08', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Gabriel_Attal', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:gabriel-attal-10'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:gabriel-attal'), 'Secrétaire général de Renaissance', 'Renaissance', null, 'nomme', 'Renaissance', '2024-12-08', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Gabriel_Attal', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:raphael-glucksmann-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:raphael-glucksmann'), 'Député européen', 'Parlement européen', null, 'elu', 'Place publique', '2019-07-02', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Rapha%C3%ABl_Glucksmann', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:raphael-glucksmann-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:raphael-glucksmann'), 'Coprésident de Place publique', 'Place publique', null, 'elu', 'Place publique', '2022-12-16', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Rapha%C3%ABl_Glucksmann', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:nicolas-dupont-aignan-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nicolas-dupont-aignan'), 'Maire de Yerres', 'Mairie de Yerres', null, 'elu', 'RPR puis indépendant', '1995-06-25', '2017-07-23', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Nicolas_Dupont-Aignan', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:nicolas-dupont-aignan-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nicolas-dupont-aignan'), 'Président de la communauté du Val d''Yerres', 'Communauté du Val d''Yerres', null, 'elu', null, '2002-03-22', '2015-12-31', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Nicolas_Dupont-Aignan', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:nicolas-dupont-aignan-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nicolas-dupont-aignan'), 'Député', 'Assemblée nationale', 'Essonne (8e circonscription)', 'elu', 'Debout la France', '1997-06-12', '2024-06-09', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Nicolas_Dupont-Aignan', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:nicolas-dupont-aignan-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nicolas-dupont-aignan'), 'Président de Debout la France', 'Debout la France', null, 'elu', 'Debout la France', '2008-11-22', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Nicolas_Dupont-Aignan', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:nicolas-dupont-aignan-5'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nicolas-dupont-aignan'), 'Président de la communauté Val d''Yerres Val de Seine', 'Communauté Val d''Yerres Val de Seine', null, 'elu', null, '2016-03-09', '2017-07-25', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Nicolas_Dupont-Aignan', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:nicolas-dupont-aignan-6'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nicolas-dupont-aignan'), 'Maire de Yerres', 'Mairie de Yerres', null, 'elu', 'Debout la France', '2026-03-22', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Nicolas_Dupont-Aignan', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:fabien-roussel-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:fabien-roussel'), 'Conseiller municipal', 'Mairie de Saint-Amand-les-Eaux', null, 'elu', 'Parti communiste français', '2014-03-24', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Fabien_Roussel', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:fabien-roussel-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:fabien-roussel'), 'Député', 'Assemblée nationale', 'Nord (20e circonscription)', 'elu', 'Parti communiste français', '2017-06-21', '2024-06-09', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Fabien_Roussel', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:fabien-roussel-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:fabien-roussel'), 'Secrétaire national du Parti communiste français', 'Parti communiste français', null, 'elu', 'Parti communiste français', '2018-11-25', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Fabien_Roussel', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:fabien-roussel-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:fabien-roussel'), 'Maire de Saint-Amand-les-Eaux', 'Mairie de Saint-Amand-les-Eaux', null, 'elu', 'Parti communiste français', '2025-01-30', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Fabien_Roussel', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:francois-ruffin-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:francois-ruffin'), 'Député', 'Assemblée nationale', 'Somme (1re circonscription)', 'elu', 'La France insoumise, puis Écologiste et Social', '2017-06-21', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Fran%C3%A7ois_Ruffin', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:francois-ruffin-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:francois-ruffin'), 'Porte-parole de Picardie debout !', 'Picardie debout !', null, 'nomme', null, '2017-02-17', '2025-06-28', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Fran%C3%A7ois_Ruffin', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:francois-ruffin-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:francois-ruffin'), 'Président de Debout !', 'Debout !', null, 'elu', 'Debout !', '2025-06-28', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Fran%C3%A7ois_Ruffin', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-tondelier-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-tondelier'), 'Conseillère municipale', 'Mairie d''Hénin-Beaumont', null, 'elu', 'Europe Écologie Les Verts', '2014-03-30', '2026-03-22', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Marine_Tondelier', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-tondelier-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-tondelier'), 'Conseillère communautaire', 'Communauté d''agglomération d''Hénin-Carvin', null, 'elu', 'Europe Écologie Les Verts', '2014-04-17', '2026-03-22', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Marine_Tondelier', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-tondelier-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-tondelier'), 'Conseillère régionale', 'Conseil régional des Hauts-de-France', null, 'elu', 'Europe Écologie Les Verts', '2021-07-02', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Marine_Tondelier', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:marine-tondelier-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-tondelier'), 'Secrétaire nationale des Écologistes', 'Les Écologistes (ex-EELV)', null, 'elu', 'Les Écologistes', '2022-12-10', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Marine_Tondelier', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:david-lisnard-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:david-lisnard'), 'Conseiller départemental', 'Conseil départemental des Alpes-Maritimes', null, 'elu', 'UMP puis Les Républicains', '2008-03-16', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/David_Lisnard', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:david-lisnard-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:david-lisnard'), 'Maire de Cannes', 'Mairie de Cannes', null, 'elu', 'Les Républicains', '2014-04-05', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/David_Lisnard', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:david-lisnard-3'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:david-lisnard'), 'Président de la communauté d''agglomération Cannes Pays de Lérins', 'Communauté d''agglomération Cannes Pays de Lérins', null, 'elu', 'Les Républicains', '2017-07-20', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/David_Lisnard', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:david-lisnard-4'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:david-lisnard'), 'Vice-président du conseil départemental des Alpes-Maritimes', 'Conseil départemental des Alpes-Maritimes', null, 'elu', 'Les Républicains', '2021-07-01', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/David_Lisnard', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:david-lisnard-5'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:david-lisnard'), 'Président de l''Association des maires de France', 'Association des maires de France', null, 'elu', null, '2021-11-17', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/David_Lisnard', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:nathalie-arthaud-1'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nathalie-arthaud'), 'Conseillère municipale', 'Mairie de Vaulx-en-Velin', null, 'elu', 'Lutte Ouvrière', '2008-03-21', '2014-04-04', false, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Nathalie_Arthaud', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_mandates (id, candidate_id, title, institution, territory, appointment_type, party_at_time, start_date, end_date, is_ongoing, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_mandate:nathalie-arthaud-2'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nathalie-arthaud'), 'Porte-parole de Lutte Ouvrière', 'Lutte Ouvrière', null, 'elu', 'Lutte Ouvrière', '2008-12-08', null, true, 'Wikipédia', 'https://fr.wikipedia.org/wiki/Nathalie_Arthaud', 'other', 'published', '2026-09-10')
  on conflict (id) do nothing;

