-- "Parcours & actes" — troisième vague de données vérifiées : la motion de
-- censure transpartisane du 20 mars 2023 (réforme des retraites), une
-- relaxe supplémentaire pour Marine Le Pen, et quatre controverses
-- documentées. Recherchées et recoupées contre des sources identifiables en
-- septembre 2026 (voir chaque source_url) — mêmes faits que
-- src/lib/data/local/candidate-records.ts, avec lequel ce fichier doit
-- rester synchronisé à la main.
--
-- Une ligne est insérée avec status = 'review_required' et non 'published' :
-- la controverse concernant la qualification des attaques du 7 octobre 2023.
-- La qualification même des faits y est contestée, y compris par le candidat
-- concerné ; c'est exactement le cas que le circuit de validation humaine
-- prévu par la méthodologie doit arbitrer avant toute publication. Elle
-- n'apparaîtra donc pas sur le site tant qu'un humain ne l'aura pas
-- explicitement passée en 'published'.
--
-- Idempotent : chaque ligne a un identifiant déterministe
-- (uuid_generate_v5), donc rejouer cette migration ne duplique rien.

-- candidate_votes — scrutin n°1240
insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_vote:1240-marine-le-pen'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'assemblee_nationale', '16e législature', '1240', 'Motion de censure transpartisane après le 49.3 sur la réforme des retraites', 'Motion déposée par Bertrand Pancher (groupe LIOT) et 90 de ses collègues, après l''engagement de la responsabilité du gouvernement d''Élisabeth Borne sur la réforme des retraites. Son adoption aurait entraîné la démission du gouvernement et le rejet du texte.', uuid_generate_v5(uuid_ns_url(), 'poliscope:theme:retraites'), '2023-03-20', 'for', 'major', true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/16/scrutins/1240', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_vote:1240-francois-ruffin'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:francois-ruffin'), 'assemblee_nationale', '16e législature', '1240', 'Motion de censure transpartisane après le 49.3 sur la réforme des retraites', 'Motion déposée par Bertrand Pancher (groupe LIOT) et 90 de ses collègues, après l''engagement de la responsabilité du gouvernement d''Élisabeth Borne sur la réforme des retraites. Son adoption aurait entraîné la démission du gouvernement et le rejet du texte.', uuid_generate_v5(uuid_ns_url(), 'poliscope:theme:retraites'), '2023-03-20', 'for', 'major', true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/16/scrutins/1240', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_vote:1240-fabien-roussel'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:fabien-roussel'), 'assemblee_nationale', '16e législature', '1240', 'Motion de censure transpartisane après le 49.3 sur la réforme des retraites', 'Motion déposée par Bertrand Pancher (groupe LIOT) et 90 de ses collègues, après l''engagement de la responsabilité du gouvernement d''Élisabeth Borne sur la réforme des retraites. Son adoption aurait entraîné la démission du gouvernement et le rejet du texte.', uuid_generate_v5(uuid_ns_url(), 'poliscope:theme:retraites'), '2023-03-20', 'for', 'major', true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/16/scrutins/1240', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;
insert into candidate_votes (id, candidate_id, institution, legislature, official_vote_id, title, description, theme_id, vote_date, candidate_vote, importance_level, featured, source_name, source_url, source_type, status, verified_at) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_vote:1240-nicolas-dupont-aignan'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:nicolas-dupont-aignan'), 'assemblee_nationale', '16e législature', '1240', 'Motion de censure transpartisane après le 49.3 sur la réforme des retraites', 'Motion déposée par Bertrand Pancher (groupe LIOT) et 90 de ses collègues, après l''engagement de la responsabilité du gouvernement d''Élisabeth Borne sur la réforme des retraites. Son adoption aurait entraîné la démission du gouvernement et le rejet du texte.', uuid_generate_v5(uuid_ns_url(), 'poliscope:theme:retraites'), '2023-03-20', 'for', 'major', true, 'Assemblée nationale', 'https://www.assemblee-nationale.fr/dyn/16/scrutins/1240', 'parliament', 'published', '2026-09-10')
  on conflict (id) do nothing;

-- candidate_legal_cases — nouvelle entrée
insert into candidate_legal_cases (id, candidate_id, title, case_type, summary, legal_status, jurisdiction, start_date, decision_date, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_legal_case:lepen-prieres-de-rue'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), 'Propos comparant les prières de rue à l''Occupation', 'Provocation à la discrimination, à la haine ou à la violence en raison de la religion', 'En décembre 2010, lors d''une réunion publique à Lyon, Marine Le Pen avait comparé les prières de rue de fidèles musulmans à une « occupation ». Poursuivie à partir de 2012 pour provocation à la discrimination, à la haine ou à la violence en raison de la religion, après la levée de son immunité de députée européenne, elle a été jugée le 20 octobre 2015 par le tribunal correctionnel de Lyon. Le ministère public avait lui-même requis la relaxe. Elle a été relaxée le 15 décembre 2015.', 'acquitted', 'Tribunal correctionnel de Lyon', null, '2015-12-15', '2026-09-10', null, 'France 24', 'https://www.france24.com/fr/20151215-marine-le-pen-relaxe-prieres-rue-musulman-occupation-nazie-france', 'media', 'published')
  on conflict (id) do nothing;

-- candidate_controversies — nouvelles entrées
insert into candidate_controversies (id, candidate_id, title, summary, event_date, context, candidate_response, candidate_response_source_url, controversy_status, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_controversy:lisnard-burkini'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:david-lisnard'), 'Arrêté municipal interdisant le burkini sur les plages de Cannes', 'Le 28 juillet 2016, quelques jours après l''attentat de Nice, David Lisnard, maire de Cannes, a pris un arrêté municipal interdisant le port de tenues manifestant de façon ostensible une appartenance religieuse sur les plages de la commune — mesure connue sous le nom d''« arrêté anti-burkini ». Plusieurs arrêtés municipaux comparables ont été pris dans d''autres communes du littoral. Le Conseil d''État a jugé le 26 août 2016, sur un arrêté similaire de Villeneuve-Loubet, qu''une telle interdiction portait une atteinte grave et illégale aux libertés fondamentales ; l''arrêté cannois a ensuite été suspendu.', '2016-07-28', 'L''arrêté a été contesté en justice par le Collectif contre l''islamophobie en France (CCIF) et critiqué par SOS Racisme. David Lisnard l''a défendu au nom de l''ordre public dans le contexte des attentats de 2016 ; ses détracteurs y ont vu une stigmatisation des musulmans.', null, null, 'documented', '2026-09-11', null, 'France 24', 'https://www.france24.com/fr/20160812-arrete-burkini-cannes-deux-associations-poursuivre-maire-cannes-justice-islam', 'media', 'published')
  on conflict (id) do nothing;
insert into candidate_controversies (id, candidate_id, title, summary, event_date, context, candidate_response, candidate_response_source_url, controversy_status, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_controversy:retailleau-etat-de-droit'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:bruno-retailleau'), 'Propos sur l''État de droit « ni intangible, ni sacré »', 'Dans un entretien au Journal du dimanche publié le 29 septembre 2024, alors ministre de l''Intérieur, Bruno Retailleau déclare : « L''État de droit, ça n''est pas intangible, ni sacré », ajoutant que « la source de l''État de droit, c''est la démocratie, c''est le peuple souverain ». La formule provoque une controverse politique et institutionnelle immédiate.', '2024-09-29', 'Parmi les réactions critiques : la présidente de l''Assemblée nationale Yaël Braun-Pivet, l''ancienne Première ministre Élisabeth Borne, le Syndicat de la magistrature et la Ligue des droits de l''Homme. Une motion de censure visant notamment ces propos a été déposée le 4 octobre 2024 par des députés du Nouveau Front populaire. Des parlementaires Les Républicains ont au contraire soutenu le ministre, affirmant qu''il évoquait « l''état du droit » et non « l''État de droit ».', 'Dans un communiqué publié le 1er octobre 2024, il dénonce de « faux débats » et affirme : « Bien sûr qu''il ne peut y avoir de démocratie sans État de droit. C''est là le fondement de notre République. »', 'https://www.franceinfo.fr/politique/bruno-retailleau-regrette-de-faux-debats-au-sujet-de-ses-propos-sur-l-etat-de-droit-fondement-de-notre-republique_6811960.html', 'disputed', '2026-09-11', null, 'Franceinfo', 'https://www.franceinfo.fr/politique/gouvernement-de-michel-barnier/l-etat-de-droit-ca-n-est-pas-intangible-ni-sacre-pourquoi-les-propos-du-ministre-de-l-interieur-bruno-retailleau-font-polemique_6810349.html', 'media', 'published')
  on conflict (id) do nothing;
insert into candidate_controversies (id, candidate_id, title, summary, event_date, context, candidate_response, candidate_response_source_url, controversy_status, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_controversy:roussel-gastronomie'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:fabien-roussel'), 'Débat à gauche après ses propos sur « un bon vin, une bonne viande »', 'En janvier 2022, pendant la campagne présidentielle, Fabien Roussel déclare qu''« un bon vin, une bonne viande, un bon fromage, c''est la gastronomie française » et défend l''accès de tous à une alimentation de qualité. La formule déclenche un débat au sein de la gauche sur l''articulation entre culture populaire, écologie et régimes alimentaires.', null, 'L''écologiste Sandrine Rousseau lui a notamment répondu que la gastronomie française inclut aussi « des raclettes suisses » et des sushis. Le directeur de campagne de Fabien Roussel a défendu des propos portant selon lui sur la hausse des salaires permettant d''accéder à une alimentation de qualité.', null, null, 'documented', '2026-09-11', null, 'Slate.fr', 'https://www.slate.fr/politique/2022-la-fabrique-dune-election/episode-38-fabien-roussel-viande-argument-electoral-carnisme-salvini-trump-johnson', 'media', 'published')
  on conflict (id) do nothing;
insert into candidate_controversies (id, candidate_id, title, summary, event_date, context, candidate_response, candidate_response_source_url, controversy_status, last_updated, next_review_at, source_name, source_url, source_type, status) values
  (uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate_controversy:melenchon-7-octobre'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:jean-luc-melenchon'), 'Qualification des attaques du 7 octobre 2023 et accusations d''antisémitisme', 'Le 7 octobre 2023, La France insoumise qualifie les attaques du Hamas contre Israël d''« offensive armée de forces palestiniennes » et estime qu''elles doivent être replacées « dans leur contexte », sans employer le terme d''attaque terroriste. La formulation, puis les prises de position de Jean-Luc Mélenchon dans les mois suivants — dont son refus de participer à la marche contre l''antisémitisme du 12 novembre 2023 — lui valent des accusations d''entretenir l''antisémitisme, qu''il conteste.', '2023-10-07', 'Le président du CRIF l''a qualifié d''« ennemi de la République » et sa position d''« abjecte ». Jean-Luc Mélenchon a justifié son absence à la marche du 12 novembre en la décrivant comme un rassemblement des « amis du soutien inconditionnel au massacre » à Gaza.', 'Il rappelle avoir appelé au cessez-le-feu dès le 7 octobre et affirme : « Nous n''avons jamais contesté le fait que des actes puissent être de nature terroriste. » Il maintient par ailleurs que l''action d''Israël à Gaza relève selon lui d''un « génocide » et non de la légitime défense.', 'https://www.franceinfo.fr/monde/proche-orient/israel-palestine/guerre-israel-hamas-jean-luc-melenchon-se-defend-face-aux-accusations-d-antisemitisme_6229194.html', 'disputed', '2026-09-11', null, 'Franceinfo', 'https://www.franceinfo.fr/monde/proche-orient/israel-palestine/guerre-israel-hamas-jean-luc-melenchon-se-defend-face-aux-accusations-d-antisemitisme_6229194.html', 'media', 'review_required')
  on conflict (id) do nothing;

