-- Nouvelles propositions annoncées lors du week-end de rentrée politique du
-- 12-13 septembre 2026 (Fête de l'Humanité, discours de rentrée RN à
-- Hénin-Beaumont).
--
-- Note sur les ids : l'id « proposal-77 » calculé par scripts/export-seed.ts
-- (position de cette entrée dans le tableau `raw`) est déjà pris en
-- production par une autre proposition (« Un mix énergétique nucléaire et
-- renouvelable », décalée là par des insertions précédentes dans ce même
-- tableau) — l'insertion sous cet id aurait donc été silencieusement
-- ignorée par le `on conflict do nothing`. On utilise ici un id libre
-- (vérifié en production) pour cette seule ligne ; seed.sql, régénéré à
-- partir du tableau local, continue lui d'utiliser « proposal-77 » pour un
-- environnement fraîchement seedé, ce qui n'est pas grave (id purement
-- interne, jamais exposé).
insert into proposals (id, candidate_id, theme_id, title, summary, description, source_name, source_url, published_at, verified_at, status, tags) values (uuid_generate_v5(uuid_ns_url(), 'poliscope:proposal:proposal-101'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:marine-le-pen'), uuid_generate_v5(uuid_ns_url(), 'poliscope:theme:logement'), 'Un « grand chantier logement » : priorité nationale et fin du ZAN', 'Fait du logement un chantier majeur du quinquennat : priorité nationale d''accès au logement social et aux APL, abrogation de la loi SRU et du ZAN, vente de logements sociaux aux occupants français.', 'Lors de son discours de rentrée à Hénin-Beaumont le 13 septembre 2026, elle a présenté le logement comme l''un des grands chantiers du quinquennat : « priorité nationale » pour l''accès au logement social et aux APL, abrogation de la loi SRU imposant des quotas de logements sociaux aux communes, autorisation de vente de certains logements sociaux à leurs occupants français, expulsion des familles « délinquantes » des logements sociaux, mise à disposition gratuite de foncier public aux promoteurs en échange de logements à prix modéré, suppression du « zéro artificialisation nette » (ZAN, qu''elle qualifie de « norme idéologique ») et de l''obligation de diagnostic de performance énergétique (DPE), remplacement de MaPrimeRénov'' par un dispositif « rénov'' à 100 % » de prêts à taux zéro, et un plan de transformation de bureaux vacants en logements.', 'ici (France Bleu / France 3)', 'https://www.ici.fr/infos/politique/henin-beaumont-marine-le-pen-veut-mettre-la-priorite-nationale-au-centre-d-un-grand-chantier-sur-le-logement-9670977', '2026-09-13', '2026-09-09', 'annonce', 'Logement social, ZAN') on conflict (id) do nothing;

insert into proposals (id, candidate_id, theme_id, title, summary, description, source_name, source_url, published_at, verified_at, status, tags) values (uuid_generate_v5(uuid_ns_url(), 'poliscope:proposal:proposal-92'), uuid_generate_v5(uuid_ns_url(), 'poliscope:candidate:fabien-roussel'), uuid_generate_v5(uuid_ns_url(), 'poliscope:theme:energie'), 'Menace de « nationalisation-sanction » des groupes pétroliers', 'Menace de nationaliser TotalEnergies et le groupe Rubis s''ils ne baissent pas leurs prix à la pompe, sur le modèle de la nationalisation de Renault en 1945.', 'À la Fête de l''Humanité le 12 septembre 2026, Fabien Roussel a menacé les groupes pétroliers TotalEnergies et Rubis d''une « nationalisation-sanction » s''ils ne baissent pas les prix des carburants, comparant cette mesure à la nationalisation de Renault en 1945, et s''adressant directement au PDG de TotalEnergies Patrick Pouyanné pour lui signifier que la gauche mettrait fin à ces profits tirés selon lui des guerres en Ukraine et au Proche-Orient. Il a aussi appelé à nationaliser une grande banque pour financer l''économie française. Aucun montant précis de baisse des prix à la pompe n''a été avancé.', 'Orange Actu (6Médias)', 'https://actu.orange.fr/politique/la-fin-est-proche-pour-ceux-qui-nous-font-les-poches-fabien-roussel-menace-les-groupes-petroliers-de-les-nationaliser-magic-CNT000002rRG36.html', '2026-09-12', '2026-09-09', 'annonce', 'Nationalisation, Carburants') on conflict (id) do nothing;
